name: Lint and test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        continue-on-error: true
        with:
          options: "--check --verbose --target-version py310"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: gcc -c -g -std=c99 runtime.c
      - run: pip install -r requirements.txt
      - run: python run-tests.py -v -l exam -c exam tests/fun tests/lif tests/regalloc tests/tuples tests/var
      - run: python run-tests.py -v -l exam -c exam tests/exam
